### ISSUE TITLE
Roadmap and task list

### ISSUE THREAD

**Issue by mmiller-max** [DeloitteDigitalAPAC/GraphQLClient.jl#1]
This issue serves as a roadmap for key features that are not yet implemented

#### GraphQL features not yet implemented

- [ ] Documents
  - [ ] Build query once and pass variables each time it is executed
  - [ ] Multiple operations in one request to a server
  - [ ] Multiple definitions in one request to a server (needed for fragments)
- [ ] Directives
- [ ] Fragments
- [ ] Inline Fragments
- [ ] Arguments on all fields (including output fields)

#### General improvements

- [x] Global client #4 
- [ ] Schema introspection
  - [ ] Improve performance of query
  - [ ] See if query needs updating
  - [ ] Can we type the schema?
  - [ ] Add tests
- [ ] Check runtime dispatch with JETTest

What introspection features/queries would be useful?
